name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install package dependencies
        run: npm install --frozen-lockfile

      - name: Build source code
        run: npm run build

      - name: Configure NPM authorization
        if: github.ref_name == 'release'
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        working-directory: ${{ github.workspace }}

      - name: Run semantic release
        if: github.ref_name == 'release'
        run: npx semantic-release
        working-directory: ${{ github.workspace }}

      - name: Fetch Latest Commit
        run: git pull
        working-directory: ${{ github.workspace }}
        # git fetch
        # git reset --hard origin/${{ github.ref_name }}

      - name: Publish npm package
        if: github.ref_name == 'release'
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --tag latest
        working-directory: ${{ github.workspace }}
